name: Docker image web
permissions:
  actions: write
  contents: read
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Ambiente
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
  workflow_call: 
    inputs:
      environment:
        required: true
        type: string
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  deploy:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      APP_NAME: paginapruebadevsecops-${{ inputs.environment }}
      IMAGE_TAG: ${{ inputs.environment }}-v${{github.run_number}}-${{github.sha}}
    steps:
      - name: Obtener version anterior
        run: |
          if [ "$ENVIRONMENT" = "dev" ]; then
            echo "PREVIOUS_VERSION=${{ vars.DEV_VERSION }}" >> $GITHUB_ENV
          elif [ "$ENVIRONMENT" = "qa" ]; then
            echo "PREVIOUS_VERSION=${{ vars.QA_VERSION }}" >> $GITHUB_ENV
          else
            echo "PREVIOUS_VERSION=${{ vars.PROD_VERSION }}" >> $GITHUB_ENV
          fi
          echo "Version anterior: $PREVIOUS_VERSION"
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build website
        run: |
          docker build \
          --platform linux \
          --build-arg APP_VERSION=${IMAGE_TAG} \
          --tag devsecopspruebas/webserver:${IMAGE_TAG} \
          -f src/Dockerfile .
      - name: Escaneo de vulnerabilidades
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecopspruebas/webserver:${{ env.ENVIRONMENT }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Publicar imagen
        if: github.event_name != 'pull_request'
        run: |
          docker push devsecopspruebas/webserver:${IMAGE_TAG}
          
      - name: Deploy DEV
        if: env.ENVIRONMENT == 'dev' && github.event_name != 'pull_request'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'paginapruebadevsecops-${{ env.ENVIRONMENT }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROFILE_DEV }}
          images: 'devsecopspruebas/webserver:${{ env.IMAGE_TAG }}'
          
      - name: Deploy QA
        if: env.ENVIRONMENT == 'qa' && github.event_name != 'pull_request'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'paginapruebadevsecops-${{ env.ENVIRONMENT }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROFILE_QA }}
          images: 'devsecopspruebas/webserver:${{ env.IMAGE_TAG }}'
          
      - name: Deploy PROD
        if: env.ENVIRONMENT == 'prod' && github.event_name != 'pull_request'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'paginapruebadevsecops-${{env.ENVIRONMENT}}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROFILE_PROD }}
          images: 'devsecopspruebas/webserver:${{ env.IMAGE_TAG }}'
      - name: Actualizar version estable
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
      
          if [ "$ENVIRONMENT" = "dev" ]; then
            VAR_NAME="DEV_VERSION"
          elif [ "$ENVIRONMENT" = "qa" ]; then
            VAR_NAME="QA_VERSION"
          else
            VAR_NAME="PROD_VERSION"
          fi
      
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/$VAR_NAME \
            -d "{\"name\":\"$VAR_NAME\",\"value\":\"${IMAGE_TAG}\"}"
          
