name : Despliegue infra IaC
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Terraform settings
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
    steps:
      - name: Validar el repositorio
        uses: actions/checkout@v4

      - name: Setup
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform init
        run: terraform init -backend-config="sas_token=${{secrets.SAS_TOKEN}}"
        working-directory: ./infra

      - name: Validacion terraform
        run: terraform validate
        working-directory: ./infra

      - name: terraform plan
        run: terraform plan -var-file terraform.tfvars -out-plan.out
        working-directory: ./infra

      -name: terraform apply
      run: terraform apply -var-file terraform.tfvars -aout-approve
      working-directory: ./infra
